<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="P4ALAP-7172XY6" name="VerificationofJson" tests="4" failures="0" timestamp="12 Aug 2021 12:34:19 GMT" time="8.755" errors="1">
  <testcase name="test_APIWithBasicAuthentication_ShouldBeGivenAccess" time="4.851" classname="VerificationofJson"/>
  <testcase name="test_NumberOfCircuits_ShouldBe20_UsingResponseSpec" time="0.003" classname="VerificationofJson">
    <error type="java.lang.Error" message="Unresolved compilation problem: 
	The method body(String, ResponseAwareMatcher&lt;Response&gt;) in the type ValidatableResponseOptions&lt;ValidatableResponse,Response&gt; is not applicable for the arguments (String, String)
">
      <![CDATA[java.lang.Error: Unresolved compilation problem: 
The method body(String, ResponseAwareMatcher<Response>) in the type ValidatableResponseOptions<ValidatableResponse,Response> is not applicable for the arguments (String, String)

at VerificationofJson.test_NumberOfCircuits_ShouldBe20_UsingResponseSpec(VerificationofJson.java:217)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- test_NumberOfCircuits_ShouldBe20_UsingResponseSpec -->
  <testcase name="test_APIWithOAuth2Authentication_ShouldBeGivenAccess" time="0.860" classname="VerificationofJson"/>
  <testcase name="test_ScenarioRetrieveFirstCircuitFor2017SeasonAndGetCountry_ShouldBeAustralia" time="3.041" classname="VerificationofJson"/>
</testsuite> <!-- VerificationofJson -->
